<head>
<script language="JavaScript" src="tomsk.js"></script>
<title>Форум. Ассоциация инженерного образования России</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<link rel="stylesheet" type="text/css" href="tomsk.css">
<meta name="Author" content="Elena Yakushkina">
</head>

<body leftmargin="0" topmargin="0" rightmargin="0" bottommargin="0" marginwidth="0"
marginheight="0" vlink="#000080" bgcolor="#FFFFFF" onUnload="javascript:unlwin();" >


<? if (!isset($pback)) {$pback="http://aeer.cctpu.edu.ru";}; ?>

<? //$path = "../../"; require( $path."backpath.inc" ); ?>

<table border=0 cellpadding=0 cellspacing=0 width=90% align=center>
<tr>
<td><img src="../mimages/spacer.gif" height=10></td>
</tr>
<tr>
<td align=right><img src="../imageslogo/aior.gif">
</td>
</tr>
</table>

<table border=0 cellpadding=0 cellspacing=0 width=100% >
<tr>
<td bgcolor=#5A7DB7>
   <table border=0 cellpadding=0 cellspacing=3 width=100%>
     <tr>
        <td><img src="../mimages/spacer.gif" width=10></td>
        <td><p class=cod><a class=acod href="<? echo $pback;?>/winn/contact.phtml">Контакты</a></p></td> 
        <td><p class=cod><a class=acod href="forum.phtml?pback=<? echo $pback; ?>">Форум</a></p></td> 
        <td><p class=cod><a class=acod href="<? echo $pback;?>/winn/map.phtml">Карта сайта</a></p></td> 
        <td align=right>